### ISSUE TITLE
Is voice change supported?

### ISSUE THREAD

**Issue by Jarly117** [BarleyFlour/VisualAdjustments2#13]
Unfortunately I couldn't find this option in current interface.

**Comment by Scanixx** [comment]
I would like that too, it was part of the older version, so helpful if you select same voice for two characters.

**Comment by NakedGranny** [comment]
Yeah, I absolutely cannot play the game without being able to select a custom voice set for custom characters. The original default voices are all just so - so - bad.

And being able to create a custom mercenary to play through the main campaign while using Rekarth's voice is just too important now.

**Comment by BarleyFlour** [comment]
Implemented in 1.1.0.
