### ISSUE TITLE
EE Picker often reverts appearance to equipment

### ISSUE THREAD

**Issue by Kryzze** [BarleyFlour/VisualAdjustments2#15]
As the the title says, often when using ee picker the saved outfit reverts to equipment and in order to fix quicksave and/or quickload is necessary. It seems to happen often after transitions from cutscenes and to different areas so far.

**Comment by Kryzze** [comment]
Found an answer to this apparent bug in the original VA comments on nexus

**Comment by KnightGabriel** [comment]
It's been over a year at this point but how did you fix it exactly? I've been having this issue for like a year straight, came back to the game today and updated the mod and it's still not fixed. I'm trying to override my banded mail armor appearance with the "mithral full plate arcane", however every time I go to the "equipment tab" or after transitions like you said it just gets added back and for some reason overrides the full plate ee I chose despite it still being there in the list.
