### ISSUE TITLE
Companion appearance / Portrait

### ISSUE THREAD

**Issue by Callimachus1** [BarleyFlour/VisualAdjustments2#22]
I'm not sure if this is a bug, or simply something that was not implemented (if it is the latter, then please add it!) but it doesn't seem to work for companions for me, when I go to a companion's "Visual" tab all I get is a blank page with nothing on it, even for portrait change... Can this be fixed?
![potr-vis](https://user-images.githubusercontent.com/115492344/194919124-9f6ab117-dc3f-4b13-b3d3-e7d525fede34.png)

**Comment by DiscipleDarkfriend** [comment]
I have this issue as well if is one however I can generate a body for companions but it completely resets their appearance.
