### ISSUE TITLE
Hide mythic not working!

### ISSUE THREAD

**Issue by EddyCosta32** [BarleyFlour/VisualAdjustments2#26]
Yes, there is already a post about this issue, but since it is being ignored I'm opening another one.
So, the option in the equipment section to hide mythic effects is not working.

On the preview it works, my angel halo disappears and all, but once I go back to the game the halo is still there.
Hope it gets fixed, because otherwise this mod is awesome, I just find it weird that this particular issue is being ignored.

**Comment by BarleyFlour** [comment]
fixed with v1.0.14
