### ISSUE TITLE
Custom colors bugged in 2.0.2c

### ISSUE THREAD

**Issue by cnieuweboer** [BarleyFlour/VisualAdjustments2#28]
**Describe the bug**

**To Reproduce**
1. Go to EE picker
2. Use the color wheel to set a custom color
3. Another color is applied to the item.

**Expected behavior**
Color is set to the custom color.

**Screenshots**
![colors](https://user-images.githubusercontent.com/55538749/197045443-3dc42c81-45d2-4439-ab9f-4fd074cc83b0.png)

**Game Info:**
 - Version: 2.0.2c

**Additional context**
I think the color sliders are multiplied by about 3. Setting RGB to 80 is more or less pure white. This happens both on existing saves and for new newly made characters.

**Comment by cnieuweboer** [comment]
Secondary colors are working properly.

**Comment by cnieuweboer** [comment]
Also, the green and blue channels are switched.

**Comment by JamesKrolak** [comment]
Yeah, you get some messed up colors if you use the color bars.  The Index options seem to work properly, but those are rather dull colors for the most part.

**Comment by BarleyFlour** [comment]
fixed with v1.0.14

**Comment by JamesKrolak** [comment]
I can confirm it's fixed.  Thanks for the quick turnaround!
