### ISSUE TITLE
Mythic Visuals

### ISSUE THREAD

**Issue by Vannner013** [BarleyFlour/VisualAdjustments2#31]
Can a way of removing Mythic Visuals be implemented? Like in EE picker remove demon skin and demon tail if you don't want to make a red demon? When you remove then on EE picker, nothing happens. When you use the equipment option to hide, the skin and tail, you keep you skin red and hair black. you set the colors right on EE picker but when you change menu the colors come back to normal. And out of the menu the tail and skin that where hidden come back.

A way to color those Mythic Visuals would also be really good to create diverse visuals.

**Comment by MysticBrightShadow** [comment]
Yes please! We need this!

**Comment by medusaplays** [comment]
Same here, getting rid of the demon red skin was the reason for downloading the mod, but it doesn't work :(
