### ISSUE TITLE
Does it not work after the update?

### ISSUE THREAD

**Issue by Orzzzzz1012** [BarleyFlour/VisualAdjustments2#35]
Does it not work after the update? When I open the game, the screen will be torn, and the relevant button will not show any content

**Comment by JSh-git** [comment]
Confirm, same issue on the latest patch  with VA2 1.1.0
![image](https://user-images.githubusercontent.com/60020139/199348333-9738a296-baa9-4980-bf4b-a1c791c352ec.png)
