### ISSUE TITLE
Massive slowdown on Main Menu

### ISSUE THREAD

**Issue by autobotcoop** [BarleyFlour/VisualAdjustments2#58]
**Describe the bug**
Once the mod is installed, the main menu has a massive framerate loss and getting in the game, the ee picker is slow/doesn't load. 

**To Reproduce**
1. Install Mod
2. Slowdown

**Game Info:**
 - Version: GOG 2.0.7o

**Comment by BarleyFlour** [comment]
You need to wait for it to recache all the assets, it does this after every update.
