### ISSUE TITLE
Latest Patch results in portraits not updating on the party bar

### ISSUE THREAD

**Issue by adammartin** [BarleyFlour/VisualAdjustments2#63]
After the latest patch the updated portraits no longer are shown on the party bar on the bottom of the screen.  It's correctly updated everywhere else (load screens, inventory, character, etc.) but not that screen.

**Comment by v-echo** [comment]
Can confirm. Perhaps a change / break in how custom portraits are handled? Changing them via save editor instead of VA2 has the same issue.

**Comment by Krollbotid** [comment]
They had bug with portrait change by shiftting in new class. So they probably changed how custom portraits are handled

**Comment by Callimachus1** [comment]
Happening to me too. Here are some screenshots.
![Seelah](https://user-images.githubusercontent.com/115492344/227597509-7775c70c-b007-41b4-adfd-5df593c7ba61.png)
![Ember](https://user-images.githubusercontent.com/115492344/227597984-118ba158-55c4-42e0-8226-16d88bc7b446.png)

**Comment by edvin76** [comment]
what about Nenio?

**Comment by CriticalFoxes** [comment]
@edvin76, I had no issues with her.

@BarleyFlour, I think you can close this and the duplicate 67.
