### ISSUE TITLE
The companion portraits in the bottom bar cannot be changed

### ISSUE THREAD

**Issue by PPDSKLL** [BarleyFlour/VisualAdjustments2#67]
**Describe the bug**
The companion portraits in the bottom bar cannot be changed, but the FullLength and Medium portraits display the changed versions.

**Game Info:**
2.1.1i

**Comment by Cava1712** [comment]
I second that. Portraits are even correct in the loading menu, just not on the ingame quickbar.

**Comment by CriticalFoxes** [comment]
FYI, this is a duplicate submission of #63

**Comment by PPDSKLL** [comment]
> FYI, this is a duplicate submission of #63
Yes,Yes, I just realized that.But I don't know how to delete issues on Github.

**Comment by RockingSisyphus** [comment]
The latest update of WotR to 2.1.2d seems to fix some issue of portraits,but still Nenio's bottom row small portraits can't be change....

**Comment by CriticalFoxes** [comment]
> The latest update of WotR to 2.1.2d seems to fix some issue of portraits,but still Nenio's bottom row small portraits can't be change....

I did not have this issue. I can confirm with just 3 Mods: Mod Achievements, VisualAdjuster2, and Cleaner, I am able to change and maintain all of their portraits, Nenio included, to what I set them as.
