### ISSUE TITLE
Stuck at main screen with VA2 Is loading resources.

### ISSUE THREAD

**Issue by Comnislasher** [BarleyFlour/VisualAdjustments2#74]
Stuck at main screen with VA2 Is loading resources. Logs show some sort of error:

> [VisualAdjustments2] [Error] System.NullReferenceException: Object reference not set to an instance of an object
>   at VisualAdjustments2.Infrastructure.Bubble_Extension_Methods.GetBeneficialBuffs (Kingmaker.ElementsSystem.GameAction action) [0x001d5] in :0 
>   at VisualAdjustments2.Infrastructure.Bubble_Extension_Methods+c.b__1_0 (Kingmaker.ElementsSystem.GameAction a) [0x00000] in :0 
>   at System.Linq.Enumerable+WhereArrayIterator`1[TSource].MoveNext () [0x0002c] in :0 
>   at System.Linq.Enumerable.Any[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00015] in :0 
>   at VisualAdjustments2.Infrastructure.Bubble_Extension_Methods.GetBeneficialBuffs (Kingmaker.UnitLogic.Abilities.Blueprints.BlueprintAbility spell) [0x00039] in :0 
> Uploading Crash Report
> NullReferenceException: Object reference not set to an instance of an object
>   at VisualAdjustments2.Infrastructure.Bubble_Extension_Methods.GetBeneficialBuffs (Kingmaker.ElementsSystem.GameAction action) [0x001d5] in <77869aee5e2642e3ae663d41e152368d>:0 
>   at VisualAdjustments2.Infrastructure.Bubble_Extension_Methods+<>c.<GetBeneficialBuffs>b__1_0 (Kingmaker.ElementsSystem.GameAction a) [0x00000] in <77869aee5e2642e3ae663d41e152368d>:0 
>   at System.Linq.Enumerable+WhereArrayIterator`1[TSource].MoveNext () [0x0002c] in <351e49e2a5bf4fd6beabb458ce2255f3>:0 
>   at System.Linq.Enumerable.Any[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00015] in <351e49e2a5bf4fd6beabb458ce2255f3>:0 
>   at VisualAdjustments2.Infrastructure.Bubble_Extension_Methods.GetBeneficialBuffs (Kingmaker.UnitLogic.Abilities.Blueprints.BlueprintAbility spell) [0x00056] in <77869aee5e2642e3ae663d41e152368d>:0 
>   at VisualAdjustments2.Infrastructure.LoaderGameObject+<LoadFXs>d__17.MoveNext () [0x00466] in <77869aee5e2642e3ae663d41e152368d>:0 
>   at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00026] in <4fae2288737c4dfda349689bbefabfcc>:0

**Comment by Wolfy339** [comment]
I came here to check. I have the same issue. Tho on patch notes it was supposed to have been resolved.

**Comment by FerrumAnguis** [comment]
Sadly it seems, that "supposed to" doesn't mean it has been solved. I have the same problem.

**Comment by BarleyFlour** [comment]
Potentially fixed with v1.2.5, if someone who had the issue could update, but remove the cache folder and then see if it is fixed, that would be great.

**Comment by Comnislasher** [comment]
Work for me. Thanks!

**Comment by FerrumAnguis** [comment]
Works :)
