### ISSUE TITLE
Mythic FX Aeon spinning orbs are disabled only in inventory screen

### ISSUE THREAD

**Issue by HeruLupercal** [BarleyFlour/VisualAdjustments2#75]
**Describe the bug**
Mythic FX (Aeon spinning orbs) cannot be hidden outside of inventory screen

**To Reproduce**
1. Be Aeon
2. Go to 'Visual' -> 'Equipment"
3. Switch 'Mythic' to 'off', the orbs disappear in that screen only,
4. Return to game 
5. The orbs are still visible on the character

**Expected behavior**
The orbs (mythic FX) should have disappeared ingame just like it did in the inventory screen, but it doesn't.

**Screenshots**
https://imgur.com/a/qqVQWHD

**Game Info:**
- VisualAdjustments 2 version: 1.2.4
- Pathfinder WotR version: 2.1.5r

**Additional context**
Thank you for your hard work, the game would be far less enjoyable without your mods!

**Comment by Vyralator** [comment]
Same  problems happens with the Demon mythic path.
According to previously closed issues this was already been fixed, but I assume some game update messed with that again. Really unfortunate I'm getting the feeling that this is one of the main features that people use the mod for.

**Comment by BarleyFlour** [comment]
Fixed with v1.2.5
