### ISSUE TITLE
Cache empty in Version 2.3.0.bb

### ISSUE THREAD

**Issue by pop1986** [BarleyFlour/VisualAdjustments2#80]
First time I have installed this mod after I came back to WOTR with "The final DLC" version 2.3.0.bb
The current version of VA2 is not made for this. So maybe that's why it doesn't work properly.
Main Issue: The Mod does not load any cached Data.
Lists for EEs, Enchants, FXs and weapons are all empty.
In weapons, I can choose the filter options, but nothing from the cached file is listed.
The other features seem to work properly.

**Comment by BarleyFlour** [comment]
Did it say it was caching things in the main menu? If so did you wait for it to finish before loading in?

**Comment by pop1986** [comment]
If that is the issue, maybe I should deactivate "Autoload last save after startup" in Bag of Tricks Mod? :-|
It doesn't actually say anything about caching, but deactivating auto load last save actually worked! Thanks.
I also have found a workaround. When I open VA with my main character, switch to a companion and go to Equipment, EE Picker or Buff FX from there, it shows the items from the cache files. From there, I can also switch back to my main Character and make adjustments there. Next to Back of Tricks, this Mod is my absolute favorite already. Why on earth did I just see it now? ^^
Thanks for the tip, I will check it out on my
