### ISSUE TITLE
Removing things from EE picker doesn't work

### ISSUE THREAD

**Issue by Sneffff** [BarleyFlour/VisualAdjustments2#81]
I'm currently playing as a Lich, and have been trying to remove the ''mythic lich desaturation'', I'm able to actually click it so that it disappears from my current EEs, but no visual change happens, and the moment i click away from the visual tab and go back to it, the mythic lich desaturation has popped back into my current list of EEs.

**Comment by BarleyFlour** [comment]
You need to hide mythic effects in the equipment tab, the game handles mythic EEs differently from normal EEs.
