### ISSUE TITLE
Hide mythic not works properly

### ISSUE THREAD

**Issue by aivengo1677** [BarleyFlour/VisualAdjustments2#9]
Game version 1.4.2a

"Hide mythic" option are not hiding demon's red skin and tail.
When I delete it in "EE picker" tab - changes are not saving ("apply button" does nothing).

**Comment by Walters-Marissa** [comment]
I guess I will add since this is being ignored that this is a road block for me too. I basically need this to play.

**Comment by RevanStarforge** [comment]
same with the lich. in fact; for lich, deleting the mythic element from EE doesnt do ANYTHING at all. disable mythic doesnt do anything either

**Comment by BarleyFlour** [comment]
fixed with v1.0.14
